apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: monitoring-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - monitoring-secret.sops.yaml
