# LGTM (Loki, Grafana, Tempo, Mimir/Prometheus) Stack for Kubernetes
# OpenTelemetry 백엔드 - 개발/테스트 환경용
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# Service를 UI와 OTLP로 분리하는 이유:
# 1. UI (3000): 사람이 브라우저로 접속 → Ingress를 통한 도메인 기반 접근 (ClusterIP)
# 2. OTLP (4317, 4318): 애플리케이션이 텔레메트리 데이터 전송 → NodePort로 직접 접근
# 용도가 다르므로 논리적으로 분리하여 보안성과 관리 효율성 향상
# Grafana UI 서비스 (ClusterIP - Ingress 전용)
apiVersion: v1
kind: Service
metadata:
  name: lgtm-ui
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: lgtm
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
---
# OpenTelemetry 데이터 수신 서비스 (NodePort - 직접 접근)
apiVersion: v1
kind: Service
metadata:
  name: lgtm-otlp
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: lgtm
  ports:
    - name: otel-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
      nodePort: 30317  # OpenTelemetry gRPC 수신: http://<node-ip>:30317
    - name: otel-http
      protocol: TCP
      port: 4318
      targetPort: 4318
      nodePort: 30318  # OpenTelemetry HTTP 수신: http://<node-ip>:30318
---
# Grafana UI를 도메인으로 접근하기 위한 Ingress 설정
# http://grafana.dead-whale.org → Grafana UI (포트 없이 접근)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lgtm-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # HTTP 허용 (필요시 true로 변경)
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.dead-whale.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lgtm-ui
                port:
                  number: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
        runAsGroup: 472
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command: [ "sh", "-c", "chmod -R 777 /data" ]
          volumeMounts:
            - name: grafana-storage
              mountPath: /data/grafana
            - name: loki-storage
              mountPath: /data/loki
            - name: tempo-storage
              mountPath: /data/tempo
            - name: p8s-storage
              mountPath: /data/prometheus
            - name: pyroscope-storage
              mountPath: /data/pyroscope
      containers:
        - name: lgtm
          image: grafana/otel-lgtm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 4317
            - containerPort: 4318
          env:
            - name: ENABLE_LOGS_OTELCOL
              value: "true"
            - name: ENABLE_LOGS_GRAFANA
              value: "true"
            - name: ENABLE_LOGS_PROMETHEUS
              value: "true"
            - name: ENABLE_LOGS_LOKI
              value: "true"
            - name: ENABLE_LOGS_TEMPO
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
            - name: GF_SERVER_ROOT_URL
              value: "https://grafana.dead-whale.org" # https로 변경 (Ingress TLS 사용 시)
            - name: GF_AUTH_GITHUB_ENABLED
              value: "true"
            - name: GF_AUTH_GITHUB_CLIENT_ID
              value: "Ov23liBH6Aks2u0iOs1G"
            - name: GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS
              value: "bottle-note"
            - name: GF_AUTH_GITHUB_ROLE_ATTRIBUTE_PATH
              value: "[login=='Whale0928'][0] && 'Admin' || 'Viewer'"
            - name: GF_AUTH_GITHUB_AUTO_LOGIN
              value: "false"
            - name: GF_AUTH_OAUTH_AUTO_LOGIN
              value: "false"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://127.0.0.1:4318"
          envFrom:
            - secretRef:
                name: monitoring-secret
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 120
            periodSeconds: 20
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
            - name: grafana-storage
              mountPath: /data/grafana
            - name: loki-storage
              mountPath: /data/loki
            - name: tempo-storage
              mountPath: /data/tempo
            - name: p8s-storage
              mountPath: /data/prometheus
            - name: pyroscope-storage
              mountPath: /data/pyroscope
      volumes:
        - name: grafana-storage
          hostPath: { path: /mnt/data/lgtm/grafana, type: DirectoryOrCreate }
        - name: loki-storage
          hostPath: { path: /mnt/data/lgtm/loki, type: DirectoryOrCreate }
        - name: tempo-storage
          hostPath: { path: /mnt/data/lgtm/tempo, type: DirectoryOrCreate }
        - name: p8s-storage
          hostPath: { path: /mnt/data/lgtm/prometheus, type: DirectoryOrCreate }
        - name: pyroscope-storage
          hostPath: { path: /mnt/data/lgtm/pyroscope, type: DirectoryOrCreate }
