---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# Service를 UI와 OTLP로 분리하는 이유:
# 1. UI (3000): 사람이 브라우저로 접속 → Ingress를 통한 도메인 기반 접근 (ClusterIP)
# 2. OTLP (4317, 4318): 애플리케이션이 텔레메트리 데이터 전송 → NodePort로 직접 접근
# 용도가 다르므로 논리적으로 분리하여 보안성과 관리 효율성 향상
# Grafana UI 서비스 (ClusterIP - Ingress 전용)
apiVersion: v1
kind: Service
metadata:
  name: lgtm-ui
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: lgtm
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: lgtm-otlp
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: lgtm
  ports:
    - name: otel-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
      nodePort: 30317  # OpenTelemetry gRPC 수신: http://<node-ip>:30317
    - name: otel-http
      protocol: TCP
      port: 4318
      targetPort: 4318
      nodePort: 30318  # OpenTelemetry HTTP 수신: http://<node-ip>:30318
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lgtm-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # HTTP 허용 (필요시 true로 변경)
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.dead-whale.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lgtm-ui
                port:
                  number: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  replicas: 0 # 메모리 문제 해결 전까지 일시적으로 0으로 설정
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      nodeSelector:
        node-role.kubernetes.io/platform: platform

      # Pod 시작 전 기존 데이터 정리 (emptyDir 효과)
      initContainers:
        - name: cleanup-old-data
          image: alpine:latest
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command:
            - sh
            - -c
            - |
              echo "=== Cleaning up old LGTM data ==="
              echo "Before cleanup:"
              du -sh /data/* 2>/dev/null || echo "No data found"

              # 데이터 삭제
              rm -rf /data/prometheus/* /data/loki/* /data/tempo/* /data/pyroscope/* /data/grafana/grafana.db

              echo "After cleanup:"
              du -sh /data/* 2>/dev/null || echo "Cleanup completed"
              echo "=== Starting fresh ==="
          volumeMounts:
            - name: lgtm-data
              mountPath: /data

      containers:
        - name: lgtm
          image: grafana/otel-lgtm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 4317
            - containerPort: 4318
          env:
            - name: ENABLE_LOGS_OTELCOL
              value: "true"
            - name: ENABLE_LOGS_GRAFANA
              value: "true"

            - name: GF_SERVER_ROOT_URL
              value: "https://grafana.dead-whale.org"

            # [로그인 폼 강제 활성화] -> "Sign in with GitHub" 버튼 보이게 함
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "false"

            # [자동 로그인 끄기] -> 무한 루프 방지
            - name: GF_AUTH_OAUTH_AUTO_LOGIN
              value: "false"
            - name: GF_AUTH_GITHUB_AUTO_LOGIN
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"

            # [로그아웃 후 이동 경로] -> 확실하게 로그인 페이지로 보냄
            - name: GF_AUTH_SIGNOUT_REDIRECT_URL
              value: "https://grafana.dead-whale.org/login"

            # --- GitHub OAuth 정보 ---
            - name: GF_AUTH_GITHUB_ENABLED
              value: "true"
            - name: GF_AUTH_GITHUB_CLIENT_ID
              value: "Ov23liBH6Aks2u0iOs1G"
            - name: GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS
              value: "bottle-note"
            - name: GF_AUTH_GITHUB_ROLE_ATTRIBUTE_PATH
              value: "[login=='Whale0928'][0] && 'Admin' || 'Viewer'"

            # --- 네트워크 설정 (내부 통신 강제) ---
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://127.0.0.1:4318"
          envFrom:
            - secretRef:
                name: monitoring-secret

          # 헬스 체크
          readinessProbe:
            httpGet: { path: /api/health, port: 3000 }
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /api/health, port: 3000 }
            initialDelaySeconds: 60
            periodSeconds: 20

          # 리소스
          resources:
            requests: { memory: "2Gi", cpu: "1000m" }
            limits: { memory: "10Gi", cpu: "4000m" }

          volumeMounts:
            - name: lgtm-data
              mountPath: /data

      volumes:
        - name: lgtm-data
          hostPath:
            path: /mnt/data/lgtm
            type: DirectoryOrCreate
