#ENC[AES256_GCM,data:tt6Jjr7gw4muIEhxkl3z2ulyHBkFuKzyO6zjasAQ2vII,iv:E1gGzf8iyjrpfsUOFw46+Vekt2EK8gBNT+UH0jWdkFo=,tag:mRASw9g/mCP3FqgF43zuNQ==,type:comment]
#ENC[AES256_GCM,data:LVpOPohge7C/TXI7hHdHqJr08GJyANR/kzxffs+UNMVs9dHUL63KamDTyNdNblWefBsF,iv:k0JIbAzG3P4Tw4E0Z+cpRUu4ESox7DEpO3uld41JSXc=,tag:E5O/Mo4Q1vQgyJZR1MKi0Q==,type:comment]
apiVersion: ENC[AES256_GCM,data:W7A=,iv:BHXLaELwEt09FvsaPKZLAXtXugxGocI00pAsFJfCHEE=,tag:dQ0LsAj5rVzPjxzrUAHhjA==,type:str]
kind: ENC[AES256_GCM,data:MJU6C+b6,iv:WYKoqatlFsDym4Owf7g/i1KSbJRTtDHKZ34Q0FNwDvk=,tag:2QnSdsNp69GGm111Xse08w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:G6J0Ufcj2r5jcslF2Duqc2w=,iv:PbEflgns52utWmnTNCByWQdiO46szav3g+ifNt34RAc=,tag:2Ptbw+5hh53jlsc09SFY+Q==,type:str]
    namespace: ENC[AES256_GCM,data:49iPXYcs50Wf+Q==,iv:P0jBDHoJgS3m3x7UcltOPPHvyjzzGlC00lEkwv7Q0KI=,tag:hpV6Y5wH/Z50Qjne1jBuig==,type:str]
type: ENC[AES256_GCM,data:abDPVxLE,iv:p/7M1YWfGGCznAgqeRAqQiuxUaONt7OumCM9cPpkcOI=,tag:0g28DLSTyrUJRmF3Ah5ZOA==,type:str]
stringData:
    #ENC[AES256_GCM,data:vI4rYy2DRnVSR0QzaWYKP3H6vvBhPFCzZQ==,iv:mR5jRfkLXvtC+BCerGiif3eD40owsssHuKDbuMcxmrQ=,tag:9NuoFnEbaqTA1E9ixBB+2w==,type:comment]
    GF_AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:0KnlCvD5eWnnEYS18kbxlaUVQNqt7fGiAzfjQPfwN5i3OomlBHeJ7A==,iv:0M65X2VRqCbOQW4vs3LkOBBU3psEMXpYfPifADAQPrA=,tag:whFKygYDt+TOSivXRem4cQ==,type:str]
    #ENC[AES256_GCM,data:eRsOxymCzqGXJZX2+G4BS7A/fXqYA8Nwv/zTNA==,iv:rbm+POlqu/2fZNP3cbAkiET6E9P9hKWhrlkrq90KjlI=,tag:qM07rSFuz6jb0b071RNeIQ==,type:comment]
    OTEL_TRACING_DISABLED: ENC[AES256_GCM,data:zajc0DI=,iv:B0Ssznr5jqcDXg6MNfmA12Amk5OVr3HC7F8gmyYzXPQ=,tag:lvPJZiycr/0+zugBHuB9LA==,type:str]
    OTEL_TRACE_SAMPLING: ENC[AES256_GCM,data:WKK2,iv:0OGwqMCkQrQJcaSeEp/dk1xG69GRukM4dnwTeHRgpeU=,tag:aW4TDs6eNWU+hfqLouUUPQ==,type:str]
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: ENC[AES256_GCM,data:wrf+H1x8BRerBXBmXUWrFUIpmamVxzGhw01/kEwJJ4sAPgSq3sxtnV0E,iv:2/8vY4sYpFMZF8TZN3NsHaPPV7wbqFzgKKonF1m6E0Y=,tag:zfoN1w+405Tk5ICBpmZEoQ==,type:str]
    OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ENC[AES256_GCM,data:UvXMs/niUiWlEWNn2urYtDqjQ+X3YcJLqXWfDy4bZoqGSoacrWWioUBA3g==,iv:m+ge9A7FEz662gK9ZX0FuNcVocjToHAbYaJv8k1kGM4=,tag:cJqwI/GUmsz8dis9MMq6YQ==,type:str]
    OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: ENC[AES256_GCM,data:uguQht9/4ysNaDwKznW/rsTbI/owPxU6ltRwB+VDP7/+jmva1nc7nw==,iv:XgIhZELgybyiI6TWI53OoCpEfJ29r9+epBS3ECYT75o=,tag:XPeCFzKXFCKZs7wuVs7BRg==,type:str]
    OTEL_EXPORTER_OTLP_TIMEOUT: ENC[AES256_GCM,data:ZcIZ,iv:6Knn+gtPdMucBwhwVO0TyjFLbtnS8DFfi+EOD/6N5nk=,tag:5MdH5TQNwhQjg3faxie71Q==,type:str]
    PROMETHEUS_ENABLED: ENC[AES256_GCM,data:kJi/RQ==,iv:I/6ANNyYikx393N5iD8uoPK5oT/P2OCZ+B0iBnco3/Y=,tag:ly+RMJbce6j90qsvgrkaFg==,type:str]
    OTEL_SERVICE_NAME: ENC[AES256_GCM,data:ZFMTgngZRykCWthZ/B/V6FYUAikFdg==,iv:p3iULeUiCljSDijnTFYNyKVRGAxHamlN5IpkdJV7iis=,tag:p9oprc1xAxu/j97LRTAVsA==,type:str]
    OTEL_RESOURCE_ATTRIBUTES: ENC[AES256_GCM,data:jYeLqAWK9CB5LaCczqyLqLi8xwYOyQ3976YdoGiatj+sSB0U,iv:aelz9GvD50+dFq94QJCH+b30D5dAQLslyolsPa9sYV8=,tag:VTg0RuGvL4UJ9ekM4v+v8A==,type:str]
sops:
    age:
        - recipient: age10625rt38awun7dcpgjq4jjgtem0mmxwhqckce2vhjjh3j2gvaq5s32gn0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDM1ROQ3hlS0lPUmo3d28y
            bHNPOXhBNXozNGl2bEltOUlQWlM0c3d3amk4Cnl0UmJOUTdEL29WTHUzMDBRN1Vy
            TUVBN01lLzhpUmxNZ28wN0hBZ0hXRzAKLS0tIC9oeDkzS1ZlbllTVFh2eFJXdkhP
            M2FuNms4WVNvTGpBSDNDQjJKS0kvUGMKcKaTiiC3T0b4jetg0ddW6payOFQlroPL
            wUoMPUQp994qTHMdcsuGCE5NCinBG1tL4jVJP3aVuu4ia1BtQbxRdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9vhwpuvaapjzxyxsttusj6p36jzrwqclfytq0jf4vvwj2vy4ehs4m4c64
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRXdQMXJiVEpOVGpVWndv
            bkdqZ0t0cFV0ZWhzdDdwWU5OVk5NU1FvWGo4CnJKbkx2MS9XRm5QUVJtVk5ONDZx
            U3FvaU9XcXUvbEZpZFRzMVFaUjlTTGMKLS0tIHFBekswSEhIMjh3T0RVb1FubFVI
            blpodEZtR04rWFZQMlJCNkpram9VSzAKYwB/VKfyolNk3g1JI/neJI74x+TWKWNB
            ea4jVNXm+mnMkKWgceCDdaCq97AlWsrUm8yamsbLrm6M66T6Y391Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T15:58:16Z"
    mac: ENC[AES256_GCM,data:0ObKFE2hH79v6JkO4st6OBg45X2ZfkNtux4yKQQHH9RaeKFshVSAs8fOn7fnyUI7MQRuWPnOYYgLX9AQ/GIuHw73mvzgPoDAZudN5ZNHSdSknQcSCw93TyROCh5VdU/fAIkpZvTiaYQ1tp2BzAhTNLcvHSsQ0qtsiRvuugOmYLQ=,iv:KFdT3TeVSLaWa2jsAupTMFW1ImEqDxT18YslNFAf8ig=,tag:RhUlN9NRGm/vj3orT2HmNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
