# HTTPRoute for Zot Container Registry
# 두 서비스가 같은 이미지 저장소 사용
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zot-route
  namespace: container-registry
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
  hostnames:
    - docker-registry.bottle-note.com
    - docker-registry.kr-filter.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: zot
          port: 5000
