#ENC[AES256_GCM,data:6X05k14xkMDkPbn6p2FmbsQfGKpczo6iXz+ZyYGxLqXX5fxz1g==,iv:gnqg8zJdn8VtbNCw2SCze0gd6NOjm0hfrSzqgR5ZrIM=,tag:bHp/z3Lz6XpeHvQ3AqQPBg==,type:comment]
#ENC[AES256_GCM,data:To+NrVHB8+RIMTnWAljdMt5aJCewsSmyN0KL5o+CIPt5jJOEOB1QaRrD4vN7avpRRs6QtFbR/Xgf4RonaTjph8CMyBSXwx7SqKe8RdfboGZwfrAmORPaWCRG,iv:jTMC8emZtQJdJCIgROmgrW4s9bNUeOy+scmjtTUYSX4=,tag:AGz31uaqDAw5DeGFVnyNfQ==,type:comment]
#
#ENC[AES256_GCM,data:jO54iKGQbd9MrxtFcPbJwXVQp1608uAW,iv:x0KkzjTrlU0A7YpokB2zRj5N4ycP2Cc7DH/8tm2IhEU=,tag:qzv21enhl1vajJsrfaeNEQ==,type:comment]
#ENC[AES256_GCM,data:UWRVEY5zEaiKHKxNmhojuiOZHV502BvieOZMyUdhAyNC24ZVh9hAWDZn04pv4F/WNQ==,iv:YV0ID8tKw2XoE7RmK+DX11K5ACsvHQzqFul2lhwuTno=,tag:obfNceOZagq6YfM6QSCKZA==,type:comment]
#
#ENC[AES256_GCM,data:vtwunxM20YN29H6elQ0ZIuT8,iv:xGDSUSq97hoOb/XRs/DHU0vjPuhKHJEmb6c4cQpdyw8=,tag:Ebc8NHQfCMqMUDsbLNX5sA==,type:comment]
#ENC[AES256_GCM,data:9cqsYEfEwrDSaDKJx0Dj6yXT7W6M9BrmPl5TNNKsDKQ69Q==,iv:6bFNm7EgMYglYqX56nFgqmMqQlrXKrBywJw3A/kzXSY=,tag:S66YsPBJ1Cb2pbjgSmH77A==,type:comment]
apiVersion: ENC[AES256_GCM,data:HPk=,iv:Uf0WTFIdVLVfL/AuwCYDGAOzGxKMCy3N86zuciyuuXo=,tag:2eBfMmE7NHOd9rHxQBC9bw==,type:str]
kind: ENC[AES256_GCM,data:Dg85udPF,iv:ZIaflu9foiUJkIkV9mRBnxyqrZXYmexKedzdd+Op9h4=,tag:7TVLHFGfs6Pwm06TZcBhiA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hhfNgh+B/Gl4398q,iv:D0TvEFzJH05zacHA5Dttd01cnuaKl7XGDuzLqXHi+tw=,tag:QhtWzFoB9qMQ6ZVyWK4pHA==,type:str]
    namespace: ENC[AES256_GCM,data:h7JZZFAsfGc0LEQtVgRMi2mj,iv:ehKsNXbsuIhjI0vZvGK033h496SSzx45byswLmQVpf8=,tag:Yc/1TE92uXgdX779gIRkVg==,type:str]
type: ENC[AES256_GCM,data:d300xhDX,iv:x6d4bR6WS96VHRu3dThgeVk4gDmEMYkhcEbJI/FJerk=,tag:1uu9cqL6s9CfUAJq/dCSiA==,type:str]
stringData:
    htpasswd: ENC[AES256_GCM,data:Z5EIr45ns7qjA0dXHqb7GRQgKnjHzc4By1JbYU3ZIMaxsmELg9U/Thk32zmDQNDGLghvLEjzUNhEsgNUyekC/KB8uQ==,iv:2Be2eY8g9PTky3JYftb274L6xTVM3G7zrV6t0W84OQ0=,tag:CQv+SbUBfJQI+lYitukH4Q==,type:str]
sops:
    age:
        - recipient: age10625rt38awun7dcpgjq4jjgtem0mmxwhqckce2vhjjh3j2gvaq5s32gn0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMDNXdGt1S0cwRFhkdU5i
            NW91WGtUTWI5RllNVi9nZHRGQlhLdlhMSkFvClhGckdKc3ZGUXBybVIxUDEyOGV0
            WWNHTEZKYlBtSC92L3VpbjRYVDFOSXMKLS0tIGI2dEcwM2t1Q1RDTUFHeHhnWVVi
            bDI1Sit4dmVZZUJpSVNmbUNPMDQvYjgK8hYIAJWK1RU741rTcxos8THjotUQRoZ3
            xweUVQeaBlfoXK55oF9iId9KdRnns9cCECNLdgoX0eCxO9omLnFU/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9vhwpuvaapjzxyxsttusj6p36jzrwqclfytq0jf4vvwj2vy4ehs4m4c64
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c3IxN2tWb01TRWxPZitZ
            Rml6OHl1QUtEMGVXN2NxYlBiMHZ3WjVoUjJFCjRNb0hLdElFOXBEL0FNNk8xMmxj
            eHVyRUprVCtYSEJHd1lXbk5pSWFyZWcKLS0tIDZaaXF6RGY1Q00yNUNNUkFaYTNP
            SzZtc05oOUovLzdPM3JMNGg3SlcvNGcKvARCWd49wxq1zJKCel2qBqL/EMqN0idQ
            fYhiEutMwUSZ+I2xTeGYluLgEtznG6SYCbFyeSEPPXTiiA5iNjOpFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T00:53:03Z"
    mac: ENC[AES256_GCM,data:uuFCLd4p3f0s+IB4qF2vbynmkoGBZO58/7UkuKuCAgkdSJcQUITsvRqP7w89/b3NXyzZj4zNaYnvDWzKR6kXRK+eGrJR5uJ7pjSV5byHt2HcaVjzPZ3pQR0IC+htdXc3N8Ej4jwyIN0/mkkmyD5vMNUtZQBQxY6wz2oFKf7x/FE=,iv:ZCTSpGXR2x/Z2eqMKQH/2JjiTyyfwOtC7JQCDxgpvsA=,tag:9+5VwDwN13+dYGten22rBg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
