# TLS Certificate for Gateway
# cert-manager가 Let's Encrypt로 자동 발급
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: envoy-gateway-system
spec:
  secretName: gateway-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - docker-registry.bottle-note.com
