# Main Gateway
# 범용 HTTPS/HTTP 리스너 - 모든 도메인 허용
# 각 HTTPRoute에서 hostname 지정
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy
  listeners:
    # HTTPS 리스너 (ingress-nginx와 포트 충돌 방지: 443 -> 8443)
    - name: https
      protocol: HTTPS
      port: 8443
      tls:
        mode: Terminate
        certificateRefs:
          - name: gateway-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
    # HTTP 리스너 (ingress-nginx와 포트 충돌 방지: 80 -> 8080)
    - name: http
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: All
