# Main Gateway - HTTP 트래픽 수신
# 포트: 8080 (ingress-nginx 충돌 방지)
# HTTPS는 인증서 설정 후 추가
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: All
