# Main Gateway - HTTP/HTTPS 트래픽 수신
# HTTP: 8080 (ingress-nginx 충돌 방지)
# HTTPS: 444 (nginx-ingress 443 충돌 방지, nginx 제거 후 443으로 변경)
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: All

    - name: https-dead-whale
      protocol: HTTPS
      port: 444
      hostname: "*.dead-whale.org"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: wildcard-dead-whale-tls
      allowedRoutes:
        namespaces:
          from: All

    - name: https-kr-filter
      protocol: HTTPS
      port: 444
      hostname: "*.kr-filter.com"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: wildcard-kr-filter-tls
      allowedRoutes:
        namespaces:
          from: All
