apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/component: image-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-image-updater
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/component: image-updater
rules:
  # ArgoCD Application 읽기 및 업데이트
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  # ArgoCD Application 상태 확인
  - apiGroups:
      - argoproj.io
    resources:
      - applications/status
    verbs:
      - get
      - list
      - watch
  # Secret 및 ConfigMap 읽기 (레지스트리 인증 정보)
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
  # Event 생성 (디버깅용)
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  # Leader Election을 위한 Lease 권한
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - create
      - update
      - patch
  # ImageUpdater CRD 관리 (v1.0.x required)
  - apiGroups:
      - argocd-image-updater.argoproj.io
    resources:
      - imageupdaters
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - argocd-image-updater.argoproj.io
    resources:
      - imageupdaters/status
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-image-updater
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/component: image-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-image-updater
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater
    namespace: argocd
