apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: default-updater
  namespace: argocd
spec:
  namespace: argocd

  commonUpdateSettings:
    updateStrategy: "semver"
    allowTags: "regexp:^v[0-9]+\\.[0-9]+\\.[0-9]+$"
    ignoreTags:
      - "latest"
      - "dev"
      - "test"
      - "snapshot"

  writeBackConfig:
    method: "argocd"

  applicationRefs:
    - namePattern: "*"
      images:
        - alias: "app"
          imageName: "docker-registry.bottle-note.com/app:v0.0.1"
          manifestTargets:
            kustomize:
              name: "docker-registry.bottle-note.com/app"
