apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: default-updater
  namespace: argocd
spec:
  namespace: argocd

  commonUpdateSettings:
    updateStrategy: "semver"
    allowTags: "regexp:^v[0-9]+\\.[0-9]+\\.[0-9]+$"
    ignoreTags:
      - "latest"
      - "dev"
      - "test"
      - "snapshot"

  writeBackConfig:
    method: "argocd"

  applicationRefs:
    - namePattern: "profanity-filter"
      images:
        - alias: "profanity-api"
          imageName: "docker-registry.bottle-note.com/profanity-api"
          manifestTargets:
            kustomize:
              name: "docker-registry.bottle-note.com/profanity-api"
        - alias: "profanity-ui"
          imageName: "docker-registry.bottle-note.com/profanity-ui"
          manifestTargets:
            kustomize:
              name: "docker-registry.bottle-note.com/profanity-ui"

    - namePattern: "chatbot-alpha-1"
      images:
        - alias: "chatbot-alpha-1"
          imageName: "docker-registry.bottle-note.com/chatbot-alpha-1"
          manifestTargets:
            kustomize:
              name: "docker-registry.bottle-note.com/chatbot-alpha-1"
