apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: image-updater-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - image-updater-secret.sops.yaml