apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seaweedfs
resources:
  - namespace.yaml
  - secret-stores.yaml
  - external-secret.yaml
  - configmap.yaml
  - seaweedfs.yaml
  - httproute.yaml
  - networkpolicy.yaml
generators:
  - ksops-generator.yaml
