apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: home-lab
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.external-secrets-system.svc.cluster.local:8080
      vaults:
        home-lab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-tokens
            key: home-lab
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cheese-lake
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.external-secrets-system.svc.cluster.local:8080
      vaults:
        cheese-lake: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-tokens
            key: cheese-lake
