apiVersion: ENC[AES256_GCM,data:6zU=,iv:6d1MmM9F38Rwj/DaBx60/CtDmTJoS2SEaWwPJks6I98=,tag:eg2lBPGyVJR6pSsG05ZM3A==,type:str]
kind: ENC[AES256_GCM,data:YZ+XWlqV,iv:zeeCt9bOLAI1nNOlXpzEZwI0JbOrPu09rl4mRO40Tzo=,tag:VHweWrVeRDwIdZvZ3CHWBg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:37+mxDWdMzZ6ghuJE3smTAeK1aNiSB0N5w65,iv:EjiPA37r8l8rT8suIicLyyvYkt+oD3eA61BtlG9Ln1g=,tag:5buVDprF2v1cwZU4bWevog==,type:str]
    namespace: ENC[AES256_GCM,data:HubMHtjS,iv:TshoZ+76H35LKoo7mmBfaLz2FhrGMBOvCFHknSTlMUc=,tag:eI7Xg+PkFogj+r4e6vbtkw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:XqFdh4VUEWUSK1Uaudmd/W0MEyyVwBjaKShw,iv:Q8FpfmQV8uSIKrIry7Rtbj+K4PnUJPMbnE/rq/5FNCE=,tag:K0YpWXbEbWuS6ucM356B4A==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:fe81PDfn,iv:gtI/U6fxMavA9U70tqPnrNTFXXAKk7Tp+fEMrDd7P9w=,tag:5x3igF+4ybNm5XhzksZn5A==,type:str]
type: ENC[AES256_GCM,data:YXbvYD0A,iv:B1BPQXwqaZB84Ao9Vtb5T9OS0WaVkkbsaAVjgY70gdQ=,tag:yX289o1PoygDutwRLPdfRQ==,type:str]
stringData:
    hermes-webhook-token: ENC[AES256_GCM,data:INkW7JHd5put497XrbQ4vchfL03Kt6D/k9uFApYpnBoPaq4zqF1zWu0nizpHuYOB766q0J6GE/HIPUyV3ta+Ug==,iv:oa7su0zLUZOSjkZjIQswzlUUSPcSV2XUnRv1e70qsS0=,tag:oBvDL9GeTDmmmR0cKfqTDA==,type:str]
sops:
    age:
        - recipient: age10625rt38awun7dcpgjq4jjgtem0mmxwhqckce2vhjjh3j2gvaq5s32gn0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQWhZVkp6WndtYVA1NW1P
            dmtVTS9DcUQvZDhIMHN5RzIrc05td3FUcUhZCk1IMmJ2RHpmcHdhNHJ3MUxOZzF3
            ckhESTU0TStxang2eWZ5a2IwUCtIK2cKLS0tIE1tcGVIeHU1S0grck9mUzBWRE9R
            WVA1S3ltRU5QUytWSmNYTXhnem16QTQKWs2HJpGrgCX0I1KoGMp/6xJj0D0ZOExS
            ZRySOSi94Ul7Kh++vGjnVnSd1e3Y28GQhq0WWsv/9baRSVRo5uzQ4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9vhwpuvaapjzxyxsttusj6p36jzrwqclfytq0jf4vvwj2vy4ehs4m4c64
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU0Z2SWF3bnVDZlN0cVJo
            OWFFVzF6U1pMVmljaDZVS1E0TWJ0cGllRkRnCjFkY2JwbzViVG92ZzNSNldQVlht
            ZG9tWUZsUFdmWTNYL2xVMWtsTWdGUUEKLS0tICtTUHpmOUtVVzdoekRiU2h1NDk1
            OENrZUZyVENSOWJqZHBOREVBeHU1bHMK2lAXk9z5WnmqTxIPAuLVW0DWcZKrBr6m
            BPennH414et4Hqo74O6q+Yqy+yMEfvHU68sfrRFiptpr38ut+s8stg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T13:34:34Z"
    mac: ENC[AES256_GCM,data:YBAWENVUqlvjuNYUD9Hjh/VHIvQP2ahu498lfvc7tx1r2olO3bMi+QR2TmBKfFEldjImCHXyUXjvzRjYe+yvmJ/FmeuwTIUel1ZVSsXqQhu5yeiBoy4LP9WshvD3X0cutKWWN3cEG+CFpnFd4Ij8F3PFfwV0kZUhESHCBBXWbtE=,iv:PS4bU5XDbwyQrL9dj0pqFykUBB14x3MKr2XkN0R31v0=,tag:c67MNa2rjlqHyjI20ar27g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
