# ArgoCD RBAC ConfigMap
# GitHub OAuth 사용자 권한 관리

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # 기본 권한: 없음 (Whale0928만 접근 가능)
  policy.default: ''
  # RBAC 정책 (Organization별 Project 분리)
  policy.csv: |
    g, Whale0928, role:admin
