# ArgoCD ConfigMap
# GitHub OAuth 및 기본 설정 관리

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.dead-whale.org
  accounts.bottlenote: apiKey,login

  # GitHub OAuth 설정 (Dex)
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Ov23liw9guPIPWzDyxLE
          clientSecret: $dex.github.clientSecret
          orgs:
            - name: bottle-note
          # GitHub username을 주요 식별자로 사용
          useLoginAsID: true
          # 모든 organization과 team 정보 로드
          loadAllGroups: true

  # Gateway API 리소스: envoy-gateway 컨트롤러가 server-side apply로 필드를 추가하여 OutOfSync 발생 방지
  resource.customizations.ignoreDifferences.gateway.networking.k8s.io_Gateway: |
    managedFieldsManagers:
      - envoy-gateway
    jsonPointers:
      - /status
  resource.customizations.ignoreDifferences.gateway.networking.k8s.io_HTTPRoute: |
    managedFieldsManagers:
      - envoy-gateway
    jsonPointers:
      - /status

  # Kustomize 빌드 옵션
  kustomize.buildOptions: --enable-alpha-plugins --enable-exec
