# Ingress NGINX Controller RBAC 설정
# ServiceAccount, ClusterRole, ClusterRoleBinding, Role, RoleBinding 통합 파일

# ========================================
# ServiceAccount - Controller용
# ingress-nginx 컨트롤러가 사용하는 서비스 계정
# ========================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
automountServiceAccountToken: true

---
# ========================================
# ServiceAccount - Admission Webhook용
# Webhook 인증서 생성/갱신 Job이 사용하는 서비스 계정
# ========================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-nginx-admission
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

---
# ========================================
# ClusterRole - Controller용
# 클러스터 전체의 Ingress 리소스를 관리하기 위한 권한
# ========================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
rules:
  # ConfigMap, Endpoint, Node, Pod, Secret, Namespace 조회 권한
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
      - namespaces
    verbs:
      - list
      - watch

  # Leader Election을 위한 Lease 조회 권한
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - list
      - watch

  # Node 상세 정보 조회
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get

  # Service 조회 권한
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch

  # Ingress 리소스 조회 권한 (핵심 기능)
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

  # Event 생성 권한 (로깅/알림용)
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

  # Ingress 상태 업데이트 권한
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update

  # IngressClass 조회 권한
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch

  # EndpointSlice 조회 권한 (서비스 디스커버리용)
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
      - get

---
# ========================================
# ClusterRole - Admission Webhook용
# Webhook 설정을 업데이트하기 위한 권한
# ========================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx-admission
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
rules:
  # ValidatingWebhookConfiguration 조회 및 업데이트 권한
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - update

---
# ========================================
# ClusterRoleBinding - Controller용
# ingress-nginx ServiceAccount에 ClusterRole 권한 부여
# ========================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: ingress-nginx

---
# ========================================
# ClusterRoleBinding - Admission Webhook용
# ingress-nginx-admission ServiceAccount에 ClusterRole 권한 부여
# ========================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-admission
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx-admission
subjects:
  - kind: ServiceAccount
    name: ingress-nginx-admission
    namespace: ingress-nginx

---
# ========================================
# Role - Controller용 (ingress-nginx 네임스페이스 내 권한)
# Leader Election 및 리소스 관리를 위한 네임스페이스 내 권한
# ========================================
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
rules:
  # Namespace 정보 조회
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get

  # ConfigMap, Pod, Secret, Endpoint 관리
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - endpoints
    verbs:
      - get
      - list
      - watch

  # Service 조회
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch

  # Ingress 리소스 조회
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

  # Ingress 상태 업데이트
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update

  # IngressClass 조회
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch

  # Leader Election용 Lease 관리 (고가용성 구성 시 필수)
  - apiGroups:
      - coordination.k8s.io
    resourceNames:
      - ingress-nginx-leader
    resources:
      - leases
    verbs:
      - get
      - update

  # Leader Election용 Lease 생성
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create

  # Event 생성
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

  # EndpointSlice 조회
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
      - get

---
# ========================================
# Role - Admission Webhook용 (ingress-nginx 네임스페이스 내 권한)
# Webhook 인증서를 Secret에 저장하기 위한 권한
# ========================================
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-nginx-admission
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
rules:
  # Webhook 인증서 Secret 생성 및 조회
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create

---
# ========================================
# RoleBinding - Controller용
# ingress-nginx ServiceAccount에 Role 권한 부여
# ========================================
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-nginx
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: ingress-nginx

---
# ========================================
# RoleBinding - Admission Webhook용
# ingress-nginx-admission ServiceAccount에 Role 권한 부여
# ========================================
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-nginx-admission
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-nginx-admission
subjects:
  - kind: ServiceAccount
    name: ingress-nginx-admission
    namespace: ingress-nginx
