apiVersion: ENC[AES256_GCM,data:ctk=,iv:Fntc0w8moBz/shRSDy5qUUAF+KgPzgcYZQrJpYzHjFE=,tag:ys8r9UN2B1lszK2m4HVS9Q==,type:str]
kind: ENC[AES256_GCM,data:UDGwQ7ez,iv:VrRad/To5NJXUJ8Di3zhdubg/JaPGsFud9RNUmavq5I=,tag:0t6/xSJBSBwUDKeODlhLxA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6KiAwk2ghVAD37gm0w==,iv:G7ImKIj9ZbKkPsGH9LuFdFkUuEraWKFXTxrlVlizcWk=,tag:pcs/fq3xgPt0YG/be7Wh8Q==,type:str]
type: ENC[AES256_GCM,data:3eJ9eBxO,iv:rv7yJxplKw7wVBHGbRAym1Lpg6It3yapyIk0+Bq5D3Q=,tag:COT5CHrFIMpb3J9qs0x36A==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:AOGpC6OuBF8+p4xURAF/vFHVeZFTK6Hvmh5A4DvzYxw=,iv:py9JyY35UmVrsczWh8BhoHPFHR7O88UpdNCINhyJ9TQ=,tag:SHTK48udgYbC2bbIanI3yQ==,type:str]
sops:
    age:
        - recipient: age10625rt38awun7dcpgjq4jjgtem0mmxwhqckce2vhjjh3j2gvaq5s32gn0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bitReGN1OXpiOWQ4cVZM
            TjNhd0RaZ1puMFJsQk5SMDBYaEdqdFA0VXhBCmlrK0tNTXNNRktuSGI5VUQwZFdv
            WitFQ2tQdEtybWlKQzV0TzRtcERqeDAKLS0tIFN5VHAxK3F1ZFlHQXcwVUJObkV1
            NzQrTC9jWXczWm03M09FOGQ0OWdGQTQKEyu9dYZnDZt/m4ccCxHYRRu7E9UDRtJY
            ML6fdtK8jEoXmVqsXdFc7+WK9LplqQcH97UnIWQe4ZqFAaa63KgBrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9vhwpuvaapjzxyxsttusj6p36jzrwqclfytq0jf4vvwj2vy4ehs4m4c64
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVGkyMzlhMFRlR0ZQNkFy
            OVVwUUIrWjUyVnBhS0RaSzZDSnpiQUp6YlZRCkdlMC9uZFNNUnBrTkFnMXNYZFhI
            MU4vVGhRV3lvU3EvMzRKblhUSDU4MG8KLS0tIFduNngwVldHZEQwbXozVEF1SGRO
            WkNkV0ppSFpvdnRyWU50RDRYUncwMlkKX7+0qp8OdlZzyYKc33FUWVky9/ROo/go
            2OcYDpGg98iT6Iq/LuxaeGAuYzZ18VzUsQhskDWHferz9lS57LMuDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T16:44:58Z"
    mac: ENC[AES256_GCM,data:wTsKctdBj5q4UxwyMOHZWDrcEtBLeP/gQSfRyZXurBZ8zL6m/HykJGVfb0ylnF3cwpKserP7X/f5nCaTqHZpqcTUSWsvDQ2ylnpiu0IpwnmXyiUvklr2AwFdyk7sl1XXKbnmilIsrY4mYN29YbxRdzxZP59KYfpcHu6twoZS+Ho=,iv:XsocFTZMRm8gHN2YzANiMFYZbo9MU/BReDiMm12ALeU=,tag:xjVMNCDOm7EvfdUeLupqXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
