apiVersion: ENC[AES256_GCM,data:5VE=,iv:itZK/+cGBGxkK4hjK39FuUXLZ/GWXib1aUmxdFg/4gg=,tag:dcgLuM+1kMtchgGhEOmUFA==,type:str]
kind: ENC[AES256_GCM,data:RmYBAL2v,iv:R8kNTNyW7+VUcYw/fY0EORe3fjh9goRPjNP1xkdpgy4=,tag:khypCr5NARcBT/S4RAGiTw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aXtqBbZRpq8=,iv:MDvd7CkYmo6eQe5l1p0lylZTyfKVi5q8iSmlrrRjxCQ=,tag:xwE7JQZJeHqlyqI4RkeZSw==,type:str]
    namespace: ENC[AES256_GCM,data:9NBT/5E8upI=,iv:9+na3+Eps55FRd8ZDcB/jk/oKVqF6Vv/1hCnsMMCeZ0=,tag:8l8FqEctFNJgYWalUKfY1Q==,type:str]
type: ENC[AES256_GCM,data:PrWSv4MV,iv:vmOqsaROvUS45WJhXA530qm3MNhiEIgTYJ8UrwotEWE=,tag:Byhsmp6bRM+jDcXUxdaicw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:Nc0XrxWZ+Mt+Fb69uIRAFt2ZF0ErrF0P0xKIqt6oDJuTunrov9x24KFFeROQTWcT8VgxQciaHXGpk9VCsBIP2W59vwaP5HVnEuq+xPbYUfwThST2vKQXlg9deHt7wxJNy63YHLi0Fq1bXdtZYddkffv6/8EzJ6PRobTfZWZxfXkNJqT4iHlwAavWdKylWt1PN2nqTuDCIX+f91ZCqaJ/Mq6T8MmgLj1x0tc878j0JyVYc1ZG5Vf9Ubvl9l385YBjFiqhMvw62wjVq9c4kCFjeg61CjaGeqJnJDFikfOkjqLRyxO4FwfsXT9Gu7/53rCTuZeSgnjRq0qEhxrWSvVDIGyyBebPEWfzzFnSGSQ96BNnccsefHr6pSYyDXV+8AKXY5tXCbzS5Uj2INwGMygfEF6skETK/pRnKqwdSEUO/J1fw9m68OBJPfh3oWlOLbXuGvSPF7AcLA9dJl93k68E9SpHNbXAf501GkGvQk/7kivipw3YKn73XRLq+2O/uDpPWue5T8UU0gtk5AgGJSknDoFUeTi0D1O6G+CTPT2y3RRXIgXaUvjI6mOL/ryshtTCYSrPIBs8N7KSBXCCw2gz9U9zHfqDcudLzBs59ALhxNEhG6zNTBQRNPKUa2AinY3o++BTiLU/R3pPy0QYD41WCwn9l66+mvfW/r6vtlrGiS7pg4/b1+RcJ59Vy6bu1WecZOfKF99Bu7snrifaQ6IfqJX9k2XIjDw+NsdbbMatJxZRFLgqvJ36FTp4SUBl+N07LEsuXqW3OP+tAB9o4bBt3y5GK0y7WAksKTASuQu9hC3CVjX6pxotJUa/S/KjrKvjTK3hxCuG58p1bIC0odb9,iv:t3GCVw57+HJuDHRj7d+TX4dNqEBU4fE1FO+vRmjhWLQ=,tag:8fv+yE9UCVs2QPp6iBS1Vw==,type:str]
sops:
    age:
        - recipient: age10625rt38awun7dcpgjq4jjgtem0mmxwhqckce2vhjjh3j2gvaq5s32gn0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ajE2bXdQdk5sUXVwaWs5
            b0lYYW1BdmpIRVB2ZGt0R01GSXp3cXJQcWtVCm5ONWp1ZlNRL1Zic3RJbzd1amFE
            MjIvM0F2SVd5QUF3RTEwQXBXTmdBT1kKLS0tIHlRUnkzMDlzQ0F3V3VGMHczbURi
            ZVhvbW9IdXAxTEJjdGx1blF0OFhHdTAK/FXzn4HIonIL2oFt1UmGuqQpqVfeTsL2
            ApcI410dIk+BMVOF6jQ5iejQGl7Iemxrf2SI1RKDD1tzIO3ugJnTOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9vhwpuvaapjzxyxsttusj6p36jzrwqclfytq0jf4vvwj2vy4ehs4m4c64
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TzdTZlE5aGxHc2Z4MVFQ
            b0lJYUFjWFY5WXNsNjFKTVlyWDZVWEJFdUdrCkRVMUhGS0dlVE1XMi90ZG5RWnJn
            djY2RS9vZ1JVRVJtQi9xc2ZyUWRrKzgKLS0tIGV1QjB6c1hWaFVkNjVUQlJjaHdn
            a1Nxb2o3M1ZGR3VtWGdLR004NGxiWmcKQgEdzV4g71K4hkBujwYo07VzBAHfO90B
            EZoA3sT/1y1lShd1EAmOJs+L0cwhWcgcufEAbD4ih4gPq5Y35O4DfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T16:52:49Z"
    mac: ENC[AES256_GCM,data:2I231eepyoA5rsOMbQjM622O5SCx656A681iohkDQlN7ccOy0jatlhc41Vbb6ShTG+dCRvW/C7l9ZzE7yI3mqphFlqCBfu6Fk3ye5ecCIxznaXX92YDuUcXt4dDWwllmASZ3Z8vGdikWq6/akh/Ys7Qk74EPJUlnESaAc8+oHuE=,iv:Fz6/Fcpcx7vMqlihieIaQiG/OCdV3PcpBap8ES3GSig=,tag:mCpDffXNHpZheO/LGrX4Pw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
