apiVersion: v1
kind: Service
metadata:
  name: warpgate
  namespace: warpgate
  labels:
    app.kubernetes.io/name: warpgate
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: warpgate
  ports:
    - name: http
      port: 8888
      targetPort: http
      protocol: TCP
    - name: ssh
      port: 2222
      targetPort: ssh
      protocol: TCP
    - name: pgsql
      port: 55432
      targetPort: pgsql
      protocol: TCP
