# nonk8s
# [Deprecated] HTTP-01 ClusterIssuer (Ingress NGINX용)
# DNS-01 방식(dns-issuer.yaml)으로 점진적 전환 예정
# 현재 bottlenote, profanity, container-registry가 letsencrypt-prod를 참조 중
# 모든 서비스가 DNS-01로 전환 완료되면 이 파일 제거

---
# Staging 환경 (테스트용 - Rate Limit 높음)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: rlagusrl928@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx

---
# Production 환경 (실제 서비스용)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rlagusrl928@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
