# nonk8s
# Gateway API용 Let's Encrypt ClusterIssuer
# cert-manager v1.14+ 필요 (ExperimentalGatewayAPISupport feature gate)
#
# 사용법:
# HTTPRoute나 Certificate에서 annotation 또는 issuerRef로 참조
#   cert-manager.io/cluster-issuer: letsencrypt-gateway

---
# Staging 환경 (테스트용 - Rate Limit 높음)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gateway-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: rlagusrl928@gmail.com
    privateKeySecretRef:
      name: letsencrypt-gateway-staging
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: main-gateway
                namespace: envoy-gateway-system
                kind: Gateway

---
# Production 환경 (실제 서비스용)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gateway
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rlagusrl928@gmail.com
    privateKeySecretRef:
      name: letsencrypt-gateway
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: main-gateway
                namespace: envoy-gateway-system
                kind: Gateway
