apiVersion: ENC[AES256_GCM,data:wGg=,iv:M+g/7kpUe1PbnKrNUTIp04H+dJCMQfEi0Ub0DX/j5Ac=,tag:oJEryBN8teqYwT2HC6wsfA==,type:str]
kind: ENC[AES256_GCM,data:3ArAN74J,iv:gGCzdMynY1jVYNSUZ8xJ0tIKSXZkB0JnjZjcFdIiNVY=,tag:DOMGkkgbiAAbWZY66KiGEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bAGMWBU1H8m9PT/CvMKISdX6IQ==,iv:FWdD8FpfWsm94IFcoHxbLApHUtAqEk8cr8IsI3L9LwQ=,tag:XpsZUpvhybJjbS68PUTBmQ==,type:str]
    namespace: ENC[AES256_GCM,data:kHHw0kpd8X1NzgHX,iv:Z/qy/X6pFzwbvRsMV7JIBbiEKHPeQLDKPIggqvmw0jE=,tag:TFKlpQozXJK3qlLCuUGFMg==,type:str]
type: ENC[AES256_GCM,data:ZHVr+WTl,iv:Nyis5Ne8aV0I5/qJ38VlCTEfNXIf9qdjmDYI3S1BVDc=,tag:dDe0MCePyBzz2IRRqml8Jg==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:XITobAwAkIIos2DI2j2tTJp3US4=,iv:RXaH/YzwqUfEko18o3mQio8tGbIBkvJP4slyuXo8qGw=,tag:1QHNamHl9FJp8Ny75iIyLQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:qpptDgcUJZi9zaWajilmgZ9WGChEnyEs0ZRJcdMVrVCT8V5mE9B69w==,iv:qz3cdylxGtFJexLNY0N98gMGOdn/PJm7oVAFunnTq+Q=,tag:lYR88ieqhwtUu9nhCnWSow==,type:str]
sops:
    age:
        - recipient: age10625rt38awun7dcpgjq4jjgtem0mmxwhqckce2vhjjh3j2gvaq5s32gn0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUit1dTVsZzJ6cHRKczJw
            U3Z6cmFQWS92Q2tlOWVvUXlqSDRtSitPNERBCnY1aWxmdVdhVjk1TG5ZMWRqc0lZ
            Y3Ixalh5MmFGdDFSVWxJeEY5TVlYZW8KLS0tIHZQYUhqV0RKYVQvV1JhOXZnTEZx
            MzQ5NWMyL21PeXh3UE05NmVIZGp5eDgKKi2zF4J2074u+KIg7vTyR/rIQad8xAlI
            o030uIAbVoSvx8UHvRq4h3FBuxQZpcza6+FnNLcu9sfZga+Jk/EvCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9vhwpuvaapjzxyxsttusj6p36jzrwqclfytq0jf4vvwj2vy4ehs4m4c64
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa1ZpOWlwSzB4WEtHUloy
            bU1mWjNRSFRTRU91bEErbklTKzUyMzlFVHpvCmx1NXJmRUlnSmIvQVlPZnNtcWZS
            MGJCclBRRm93MVQyL0tSbnVTYVUrSE0KLS0tIDdxKzVJUEVrQnFya2ZHU09randO
            dzVwL3h2QlFhVmZXT29yM1dkRnF2ckEKRFyLAotj8tWRhahZwOMcszrLZrMhPBhb
            8GkDS+uTE4gWjlwqx0K42l9QXD2l/7NIUQCkZHyEWg9x1asW+kojTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T07:23:21Z"
    mac: ENC[AES256_GCM,data:J+4QI/G6pYayzOJVKr9M058ID5mf4od6Es1RBqAcu8ZFcbYWZaf/MoVxTmy7uWsKpLRVnkYFgjKhmdOMNgpjRDgGxJfeCUyFT0sE/TBlj7dsBeRu3otgqNogMwmDvEGhETxVRkzaBWUlHX7boKu3WNCzXQSJCnAwuMHJCfqxBJc=,iv:JPFVJTK6LTTEGKhpWvReOShb8iMe2ES+3P4KzFUni4U=,tag:vJ7D6PjGB4fdQbRnGfgdoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
