apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: silo-root
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: onepassword-store
  target:
    name: silo-root
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: root-user
      remoteRef:
        key: silo-admin
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: root-password
      remoteRef:
        key: silo-admin
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
