apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: silo-connect-token-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - op-token-secret.sops.yaml
