apiVersion: v1
kind: Secret
metadata:
    name: op-token
    namespace: silo
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:565dSUzm+PuKHTEtTZnzXUeZYDi8jseEGCLjgJKJ2ZUFYN/zOsfzcoH3thSTS5eM31uc0KuMTjp2RGDlmzVSfGLwcTRp5/SbTooDbPS7bGmQaXbarfeharebQkeHxmzuugrjEitFpxtPfsN7D/OMLVaMElcU66AvoHf85TwN3rQweNH3hkiYbejvJLCb+ZUGeHtvPBSDCIeTKCjAYKJzL75W952Z0q1u+vOVyqDcA1esu+ffb7K3pmPWTHCEjQtXCDcBKu5ZrAdQ9J8E89ERJjaYURrCu2rKyE7Lt9ACP7NcnfOQ/TIlrcaYWBZcFTGy3dkCdliIlO+qnv5I+J3IrPHdJ0ZLVJ7GCFRxKTpPI2eAuL8ROi/zEEvVZkBB51G51YUAzT+YhHMy6/zJ2/B4sMx6HINt7oVAAwN3ne4Lu9E9l/+oDr80Bfww5IyhbDzQeNlJY1eobB0cUZcCh2SgoS1zerQ91Vqbd7WjyVP188gpOmBQVJr6dhGy8x7j1vAjpSVBJ2TLQkIArrheSmdVUDyM9FbLxrWt1Z7jbJQGHJ2c8ogEm3R9V6qZcUDHSi13amuVgSomZbxrE32FfSf23jp3eA+IRabOXMWbxUD7yf1c46vA72R+YziS+BZHoLrX2B/zKNfwpfJAlxkQrtrkr0fdzevNF2M2Bk26sF1LD3DtOMG024xoff4IJ+Q+N7GJg7mPUER8+R+EIexZQiftIkUGmnO3XUcLOi9BtKGHAVWSSivFilUIfAWhFuz7kB9Lo6wE+FiX5esMZ2jP6mSiV8qlyBVe0qrStXMEv0GBGtjuVr7oJOEa++acqDBmoGK9tR27X4lkM9nJKQUdY59K,iv:z4GTXySG8RRwb1cyV4LBjPZwhjDM1lXhfIbmli/Xdr4=,tag:3SRuWwKTfX8WxuHMD+Eowg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybk53anVITUpXZU1tRFZw
            VVJJWjR3ZWlhNHhpZHNuckJPRjBQRi9yMXpvClg2MnVraGxPWGNoY3IyakY1VVp5
            ZG9CaDEyVDBsakFyeFlqdnJ4MTRKc0kKLS0tIEJCTjVxdmx3OE5kUGRoeEdqeGhE
            YmpjbDhpMklpQThMbWhQTHNITjVzUDgKOTNz19DLwCDxTs6ryMggitZg4f/M+4H1
            lu8EjJIjgdKTFOmFKugPxnVXKeOoqJOVpitjhcRZrZBI+lUGpIAhQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10625rt38awun7dcpgjq4jjgtem0mmxwhqckce2vhjjh3j2gvaq5s32gn0w
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbVFUZzB4TUpLMEVtWVZS
            RU9JRjF6YTE5NE9CamxyMmxwZXBwRURIdmxrCitWdExwTDhuclkrUyt4QzJlVU1D
            MDdkOVlJSDgzWWVwTjF4bUlpVmVVM1kKLS0tIEVLTGgwcFBpNWwrUmIrQ0x5QmFs
            WjZyb2hJSnhhQzFQN0RKVi9KVitiSXcKHpVYeTOPzdpdr41u0QDn2MX3Keg+8kWm
            ub6dRCfWVtl6rUtVTjDv8Vqe8I7tovYEQ99uE1TVAz+YWDDrws3J2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z9vhwpuvaapjzxyxsttusj6p36jzrwqclfytq0jf4vvwj2vy4ehs4m4c64
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T04:41:19Z"
    mac: ENC[AES256_GCM,data:OVo13f00O+oV0kkgYmqagiuDvlANe/zzu3MaQktloiARu5OwLG1QLQHHKlHHfpqTNRx5Do4ykj7POYW0gfeXmgNZloW4lVADsKEmJbKq27PVBBZYbyDuYKtWm1EHAq7W1wCSs/y3viilKkzlzZsfgPAeQ+h38lQQeVfT8F4QnFk=,iv:Le+8UAe8+t90NJ3Iux2sgts+Bsqg9AFoaVR8PujGkpA=,tag:X4nRCZFpQ82tNgflFEcEgw==,type:str]
    version: 3.13.3
