#ENC[AES256_GCM,data:J6OE/4XOUDsXt/pjrp2yEdkwma75zUnieYsS6EPbZp5PxMjO+jvVc8R5BRoq,iv:F7zFbF8Wl/Z2eoMKJJqmwO7ordpyhl2YXwZPrSxWyhw=,tag:7zCmNKgJUMhkTZAcdx2RBA==,type:comment]
#ENC[AES256_GCM,data:CmGpLk5rPFVEE43TKN2b6zPxaZoT2XvsghNnBk5NLwdXVZwAE6R0gFcsc8giJ00uod7D5VZiu4Oyg1fX/Te+aLVZ61Fc9kgRSHovHQQzQmk1z5LhhalHoXsU5GZZY9chD08=,iv:BINfiNI3X5w8yx3ixcGN/piuO93xGSRzhV0QDE08sj4=,tag:G6q49f05AlMjBvOUwRlOdA==,type:comment]
apiVersion: ENC[AES256_GCM,data:4oE=,iv:u3uh2i7A1BszCLfBxOeO9KYcQifwmNFKdnctY+AeAjE=,tag:s18HeJk3fqZP2nNhcJCr2g==,type:str]
kind: ENC[AES256_GCM,data:GdYsSaOx,iv:DR7VTRlA7ojFldZLI3S1LdfGMsSbtq8kjpXAqjHjmK4=,tag:TMQ3phbuSdl5lgMVPxcU8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ovVh+LS46AfAHRvj87OF,iv:VZcGorqVxP5RsoCZDqQC/S3gJuTexdahn+1oWmuhfUA=,tag:C7zqqDqLKLZIwC0oO61qdA==,type:str]
    namespace: ENC[AES256_GCM,data:duzTjUO2HwLc+A==,iv:KyoJ5a4XEdckKUDRWXvmv9GY79Gs7jzkmWu7Ykx76PU=,tag:o5eQ0CFWdumTBKI66XhlGw==,type:str]
type: ENC[AES256_GCM,data:sypWvCFy,iv:awkne7waTmnTtzKOB/cvCdfwRVSwspMR1BcTaSyoEuU=,tag:E9v24Q5VCfHgG1BxzluUfg==,type:str]
stringData:
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:b+iT6nZejP4AKbJVwDZNTIX+pb8+s8NyD7OOTmR/8fU=,iv:1zhAaMLOonPe3CPjtewuhG1dshc5lE9u6d+vFmjqInU=,tag:Fs0wMFwM2Wv5s6jefvBnJw==,type:str]
sops:
    age:
        - recipient: age10625rt38awun7dcpgjq4jjgtem0mmxwhqckce2vhjjh3j2gvaq5s32gn0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMHZ5UENaemJ1M3lUV2pM
            WnFtWW5VTGFPWkRIZklWRWVTRVk0WG15SUhRCkxpVEJBZEJ0ZjZMUnVGbUVBa1FY
            S09VdGpjYm9vRyt2OURhV3dSZHVGWlUKLS0tICtlSWlOQ0V2T215UTFnTDc1T0Rr
            TzhSb0FKOWt5bnU4RnFNVWNYZE9wOVkKA0vZERQ466VDQYIHV+RAWn6wpDPzNQGy
            tzwyEdrXxsnOHb68RgVTINflFIrM5cerQO7nXjA5riRErncfCOXoow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9vhwpuvaapjzxyxsttusj6p36jzrwqclfytq0jf4vvwj2vy4ehs4m4c64
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWGFNc2RveGJzQ1c1N1J4
            N1lZMldMa0k2djZSUTF4dytubHArYUVjK0FRCmh3eU5zY3l1RnlvS3FPQnhUS20w
            ODdUWUowK3RGMUJyR1V0cXhWbGEyTTAKLS0tICsvODB4eVl1b0gvOEZwU3ZDb1Vu
            UGNRN094cTZFMURVQ3pZOTd1SVFnNkEK436s/pKSmhGrPrfmbeSm7l+fwDohmIWD
            42RHXO45EIqyf8PDTNOv7sUpM5+kV1G5B8bdWdAhW7PZM3eYEcwalg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T07:15:33Z"
    mac: ENC[AES256_GCM,data:p+lgifLNlEUjlo73/sp/wxFO1rU54zqH/oF7HAuOh78DbIhyk8+oPmPVoP/BBqftpgbIMhV+y4E8irHK+X9+t5ls2JOhhPtt99kZWQYwbTiy3iBF5TszlVa1q8/TRRPUbmHjOBtquSyWCq8NjF5ElK913aAhgnESnlQ0JJQQ9Cc=,iv:6JOp5TgbUMS+cNbh0oUoH/fKoj3QZmWMoDl8bRDcghs=,tag:KbVxHZ+9Ckr3mx7RiCu5Og==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
