apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect
  namespace: external-secrets-system
  labels:
    app: onepassword-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
    spec:
      containers:
      - name: connect-api
        image: 1password/connect-api:1.7.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: OP_BUS_PORT
          value: "11220"
        - name: OP_BUS_PEERS
          value: "localhost:11221"
        - name: OP_HTTP_PORT
          value: "8080"
        volumeMounts:
        - name: credentials
          mountPath: /home/opuser/.op/1password-credentials.json
          subPath: credentials.json
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3

      - name: connect-sync
        image: 1password/connect-sync:1.7.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        env:
        - name: OP_BUS_PORT
          value: "11221"
        - name: OP_BUS_PEERS
          value: "localhost:11220"
        - name: OP_HTTP_PORT
          value: "8081"
        volumeMounts:
        - name: credentials
          mountPath: /home/opuser/.op/1password-credentials.json
          subPath: credentials.json
          readOnly: true
        - name: shared-data
          mountPath: /home/opuser/.op/data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

      volumes:
      - name: credentials
        secret:
          secretName: onepassword-credentials
      - name: shared-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: external-secrets-system
  labels:
    app: onepassword-connect
spec:
  type: ClusterIP
  selector:
    app: onepassword-connect
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
